name: http4s Flake Steward

on:
  schedule:
    - cron: '45 7 * * 2'
  workflow_dispatch:

jobs:
  lockfile:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - http4s/blaze
          - http4s/http4s
          - http4s/http4s-curl
          - http4s/http4s-dom
          - http4s/http4s-jetty
          - http4s/http4s-servlet
          - http4s/http4s-tomcat
          - http4s/http4s-jdk-http-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ matrix.repo }}

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: 207529
          private-key: ${{ secrets.STEWARD_PRIVATE_KEY }}
          owner: http4s

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@da03c0f078bc4b2c37ee4f7e072d34bf8f188bb3 # v29
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update/flake-lock
          git-author-email: 106843772+http4s-steward[bot]@users.noreply.github.com
          git-author-name: http4s-steward[bot]
          git-committer-email: 106843772+http4s-steward[bot]@users.noreply.github.com
          git-committer-name: http4s-steward[bot]
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
