name: http4s Flake Steward

on:
  schedule:
    - cron: '45 7 * * 2'
  workflow_dispatch:

jobs:
  lockfile:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - http4s/blaze
          - http4s/http4s
          - http4s/http4s-curl
          - http4s/http4s-dom
          - http4s/http4s-jetty
          - http4s/http4s-servlet
          - http4s/http4s-tomcat
          - http4s/http4s-jdk-http-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: ${{ matrix.repo }}

      - name: Install Nix
        uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: 207529
          private-key: ${{ secrets.STEWARD_PRIVATE_KEY }}
          owner: http4s

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6 # v28
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update/flake-lock
          git-author-email: 106843772+http4s-steward[bot]@users.noreply.github.com
          git-author-name: http4s-steward[bot]
          git-committer-email: 106843772+http4s-steward[bot]@users.noreply.github.com
          git-committer-name: http4s-steward[bot]
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
