name: http4s Steward

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency: steward

jobs:
  steward:
    runs-on: ubuntu-latest
    name: http4s Steward
    env:
      SBT_OPTS: -Xmx3G
    steps:
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
    
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
          
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: 207529
          private_key: ${{ secrets.STEWARD_PRIVATE_KEY }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@708c1d682b14b9785201afb25c8ffece0a9d126f # v2.90.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          repos-file: 'repos.md'
          author-email: 106843772+http4s-steward[bot]@users.noreply.github.com
          author-name: http4s-steward[bot]
