name: http4s Steward

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency: steward

jobs:
  steward:
    runs-on: ubuntu-latest
    name: http4s Steward
    env:
      SBT_OPTS: -Xmx3G
    steps:
      - uses: sbt/setup-sbt@66fb4376e81982c7d92a4074170846fff88e2e30 # v1.5.0
    
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
          
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: 207529
          private-key: ${{ secrets.STEWARD_PRIVATE_KEY }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@ff09222640622d474d0d9f93c04aefedd125b187 # v2.92.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          repos-file: 'repos.md'
          author-email: 106843772+http4s-steward[bot]@users.noreply.github.com
          author-name: http4s-steward[bot]
