name: Validate Steward Config
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: coursier/setup-action@3174df5c784a0c8724f06b7924b849551c40c39e # v3.0.3
      with:
        apps: scala-steward
    - run: scala-steward validate-repo-config .github/.scala-steward.conf
