name: Validate Steward Config
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: coursier/setup-action@648df969f41ef15fda2baba8b37f9fa3d16390a3 # v3.0.4
      with:
        apps: scala-steward
    - run: scala-steward validate-repo-config .github/.scala-steward.conf
